# Generated by Django 5.1.15 on 2026-09-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='slug',
            field=models.SlugField(blank=True, help_text='Set automatically when the submission is published; used in its public URL.', max_length=330, null=True, unique=True),
        ),
    ]
