# Generated by Django 5.1.15 on 2026-09-27 20:45

import django.core.validators
import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_published_at_submission_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionversion',
            name='brief_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='compilation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='compilation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPILED', 'Compiled'), ('FAILED', 'Failed'), ('NOT_FOUND', 'Design Brief PDF Not Found')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='compiled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='compiled_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submissionversion',
            name='file',
            field=models.FileField(upload_to=submissions.models.submission_version_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'pdf'])]),
        ),
    ]
