# Generated by Django 5.1.15 on 2026-09-29 06:54

import django.core.validators
import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submissionversion_brief_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionversion',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='storage_path',
            field=models.CharField(blank=True, help_text='Supabase Storage object path/key', max_length=500),
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='upload_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=30),
        ),
        migrations.AlterField(
            model_name='submissionversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.submission_version_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'pdf'])]),
        ),
    ]
